# add file metadata to uploaded_documents

Revision ID: bfc7b46a92e9
Revises: 20240507_01_init
Create Date: 2026-05-07 04:30:28.881107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc7b46a92e9'
down_revision: Union[str, None] = '20240507_01_init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
